### ISSUE TITLE
Replace Collaborators with video section

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#10]
Replace the collaborator section with you tube  videos uploaded by vibhav  on https://www.youtube.com/channel/UCt8W-_urFuy3dqulfQvk8fQ

![image](https://user-images.githubusercontent.com/72870037/96430774-36a57a80-1220-11eb-989d-6bb8cfbdab12.png)

note: keep the scrolling effect as it is , do not change

**Comment by VaishnaviSood** [comment]
@Vibhav-NITH  I want to work on this issue....

**Comment by Vibhav-NITH** [comment]
@VaishnaviSood go ahead!
replace the images with the videos present at https://www.youtube.com/channel/UCt8W-_urFuy3dqulfQvk8fQ
