### ISSUE TITLE
Add a toggle button to switch in between themes

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#11]
Add a button on the site that will change the theme from light to dark and dark to light when click 

![image](https://user-images.githubusercontent.com/72870037/96431102-af0c3b80-1220-11eb-8c60-de0d460731f0.png)

Hint: You can inspect the hacktober fest official website

**Comment by akshsharma1218** [comment]
@Vibhav-NITH I would like to work on this issue.

**Comment by Vibhav-NITH** [comment]
@akshsharma1218 go Ahead!
