### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#12]
Make relevant changes required in the footer section 
eg: remove unnecessary titles and add relevant titles and images 

![image](https://user-images.githubusercontent.com/72870037/96431496-3659af00-1221-11eb-8b38-204c3f5b5ae2.png)

**Comment by Yashs911** [comment]
@Vibhav-NITH I would like to work on this issue can you please guide me on what all changes do I need to make.

**Comment by Dishebh** [comment]
@Yashs911, assigned you an issue, you can work on this after completing the assigned one :)

**Comment by Vibhav-NITH** [comment]
@Yashs911 You may start working on this!

happy contributing :)

**Comment by Yashs911** [comment]
@Vibhav-NITH What all changes do I need to make.

**Comment by nabinNath** [comment]
what can i add in the footer section and what to remove?

**Comment by Yashs911** [comment]
@Dishebh @Vibhav-NITH What all changes do I need to make?

**Comment by Yuvraj-kadale** [comment]
> 
> 
> @Dishebh @Vibhav-NITH What all changes do I need to make?

@Yashs911 

replace
Armor -> vibhav and its logo
working hours-> active during fest NIMBUS
Couses-> remove the entire section
our gallery -> replace the images with the images attached in workshop section
News letter-> contact us

at last , in the bottom right corner and social media icons (fb, insta, twitter, etc) and hyperlink them

**Comment by Vibhav-NITH** [comment]
@nabinNath if we didn't get a PR from @Yashs911 within a week , the issue will be passed on to you!
in the mean while you can contribute to some other issue :)
