### ISSUE TITLE
fix header buttons

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#13]
Unlink the header buttons from colorlib and Redirect them on the same page 

![image](https://user-images.githubusercontent.com/72870037/96432266-432ad280-1222-11eb-8ba8-bd2c913bc833.png)

**Comment by Yashs911** [comment]
@Vibhav-NITH I would like to work on this issue can you please guide me on what all changes do I need to make. Do I need to unlink the home button??

**Comment by Dishebh** [comment]
@Yashs911, yes, unlink all the routes to cololib and instead, redirect to the homepage.
