### ISSUE TITLE
Add relevant text

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#14]
Remove the sample texts and add relevant text where ever required.

few samples attached:

![image](https://user-images.githubusercontent.com/72870037/96434242-057a7980-1223-11eb-8989-4bf6a66fcf86.png)

![image](https://user-images.githubusercontent.com/72870037/96434344-0b705a80-1223-11eb-9409-09f5b64581e8.png)
![image](https://user-images.githubusercontent.com/72870037/96434473-14612c00-1223-11eb-829c-e3ac2c1fd278.png)

**Comment by Sawsanalshaghel** [comment]
can I work on this

**Comment by Vibhav-NITH** [comment]
closing with #27
