### ISSUE TITLE
Fix the project buttons

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#15]
redirect the project buttons in the same section 

![image](https://user-images.githubusercontent.com/72870037/96439810-ac134a00-1224-11eb-8142-675c551986c8.png)

help!? : You can inspect the portfolio section here https://learning-zone.github.io/website-templates/rocket-business-bootstrap-free-responsive-web-theme/

**Comment by VaishnaviSood** [comment]
@Vibhav-NITH ...I want to work on this issue...

**Comment by Vibhav-NITH** [comment]
@VaishnaviSood Go ahead!

**Comment by VaishnaviSood** [comment]
#37

**Comment by Vibhav-NITH** [comment]
closing via #37
