### ISSUE TITLE
Add visitors counter in footer

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#17]
Add a display  in the footer to keep a track on number of visitors

**Comment by akshsharma1218** [comment]
@Vibhav-NITH I would like to work on it.

**Comment by Yuvraj-kadale** [comment]
@akshsharma1218 You have to add a counter that will keep counting the number of visitors !

![image](https://user-images.githubusercontent.com/43489758/96760394-889ff900-13f6-11eb-9520-389b7696e0a0.png)
