### ISSUE TITLE
One of the image is inverted

### ISSUE THREAD

**Issue by Tamanna4203** [Team-Vibhav/Team-Vibhav.github.io#22]
May be due to it's orientation . I can solve this issue.

![IMG-20201019-WA0059](https://user-images.githubusercontent.com/73111705/96492794-cb7c9800-1261-11eb-8b90-da400ddc5a33.jpeg)

**Comment by Yuvraj-kadale** [comment]
> May be due to it's orientation . I can solve this issue

@Tamanna4203 please provide a preview/attach a screenshot

**Comment by Tamanna4203** [comment]
@Yuvraj-kadale sir I have provided the preview . You can check it out

**Comment by Vibhav-NITH** [comment]
@Tamanna4203 try clearing your browser cache ! the image looks fines !
![image](https://user-images.githubusercontent.com/72870037/96498500-c15e9780-1269-11eb-8cc4-acf606c02057.png)

still if the issue  persists it will be corrected with #18

**Comment by Tamanna4203** [comment]
Ok sir
