### ISSUE TITLE
Displaying navbar

### ISSUE THREAD

**Issue by Tamanna4203** [Team-Vibhav/Team-Vibhav.github.io#23]
Navbar is not fixed on homepage . It comes after scrolling.I can fix this problem.

**Comment by ketann26** [comment]
I would like to fix that.

**Comment by Kingslayer4515** [comment]
i will do it

**Comment by Vibhav-NITH** [comment]
> Navbar is not fixed on homepage . It comes after scrolling.I can fix this problem.

@Tamanna4203 go ahead!

**Comment by Vibhav-NITH** [comment]
@ketann26 , @Kingslayer4515  the issues are assigned on first come first serve basis. If we didn't receive any PR from @Tamanna4203  within a week , the issue will be pass on to you! 

In the mean while you can contribute to other issues!

**Comment by Yuvraj-kadale** [comment]
The navbar is fixed now, with the background update!
