### ISSUE TITLE
Fix YouTube icon

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#34]
![image](https://user-images.githubusercontent.com/72870037/96916283-f7e41e80-14c4-11eb-880b-7c35542a9f36.png)

icon display glitch!

**Comment by akshsharma1218** [comment]
@Vibhav-NITH i would like to work on this.

**Comment by Dishebh** [comment]
Go ahead :+1:
