### ISSUE TITLE
Redirect the navbar to thier respective section on page.

### ISSUE THREAD

**Issue by Yuvraj-kadale** [Team-Vibhav/Team-Vibhav.github.io#40]
![image](https://user-images.githubusercontent.com/43489758/97134992-0ce6d900-1775-11eb-9d9c-c53b1ae593b7.png)

when about is click , it should scroll down to about section on the page.
similarly, workshop and contact

**Comment by VaishnaviSood** [comment]
@Vibhav-NITH  I want to work on this issue...
