### ISSUE TITLE
Redirect Footer Icons

### ISSUE THREAD

**Issue by VaishnaviSood** [Team-Vibhav/Team-Vibhav.github.io#42]
Redirect the footer buttons to the respective pages of Vibhav.

![WhatsApp Image 2020-10-26 at 10 17 47 AM](https://user-images.githubusercontent.com/61686542/97180555-3a0ca900-17c0-11eb-90e6-b00d7f43805d.jpeg)

**Comment by VaishnaviSood** [comment]
@Vibhav-NITH  I want to work on this issue.

**Comment by Dishebh** [comment]
@VaishnaviSood , sure :)

**Comment by Yuvraj-kadale** [comment]
closing via #43
