### ISSUE TITLE
Update footer layout and color

### ISSUE THREAD

**Issue by ObiWanRohan** [Team-Vibhav/Team-Vibhav.github.io#47]
The background color of the footer needs to be darkened and the size of the footer needs to be adjusted to match the content. 
The empty background color seems out of place.

Current
![image](https://user-images.githubusercontent.com/18901839/97540412-9bfc2700-19e9-11eb-87ef-ab3518efcb56.png)

Suggestion
![image](https://user-images.githubusercontent.com/18901839/97540501-bcc47c80-19e9-11eb-8516-a07edba97487.png)

**Comment by Yashs911** [comment]
@ObiWanRohan @Dishebh I would like to work on this. Which color should I use

**Comment by Yashs911** [comment]
![footer](https://user-images.githubusercontent.com/64412143/97579020-93224a00-1a17-11eb-98d2-196d23de48dd.JPG)

**Comment by ObiWanRohan** [comment]
This seems nice. Also make sure to check the dark mode color.

**Comment by ObiWanRohan** [comment]
> What color should I use?

Use the same header color, or a slightly lighter shade.

**Comment by Yashs911** [comment]
> Use the same header color, or a slightly lighter shade.

![Capture](https://user-images.githubusercontent.com/64412143/97583217-b13e7900-1a1c-11eb-96b2-f7544c09c9ab.JPG)
@ObiWanRohan
