### ISSUE TITLE
STEP IN background is different in dark mode

### ISSUE THREAD

**Issue by Yashs911** [Team-Vibhav/Team-Vibhav.github.io#57]
In dark mode STEP IN background is same as LEARN MORE but in light mode it is white
![1](https://user-images.githubusercontent.com/64412143/98277180-10703080-1fbd-11eb-90fa-7cd1831bf5c3.JPG)
![Capture](https://user-images.githubusercontent.com/64412143/98277186-11a15d80-1fbd-11eb-8c08-99db75c2b5d7.JPG)

**Comment by Dishebh** [comment]
In light mode, make the `learn more`, please make the background as white and font color the same as `step in`.
