### ISSUE TITLE
fix video play button

### ISSUE THREAD

**Issue by Vibhav-NITH** [Team-Vibhav/Team-Vibhav.github.io#6]
![image](https://user-images.githubusercontent.com/72870037/96428914-f3e2a300-121d-11eb-94a6-d171dd732c82.png)

**Comment by akshsharma1218** [comment]
@Vibhav-NITH I would like to work on this.

**Comment by Yuvraj-kadale** [comment]
@akshsharma1218 go-ahead!✌️

**Comment by Vibhav-NITH** [comment]
@akshsharma1218  reverting back your PR...the issue is still not solved!

![image](https://user-images.githubusercontent.com/72870037/96749645-b2eaba00-13e8-11eb-9131-b2c060ab8b27.png)

video won't play , try fixing !
